# infra/helm/cybersathi/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cybersathi-backend
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: cybersathi-backend
  ports:
    - port: {{ .Values.service.port | default 8000 }}
      targetPort: 8000
      protocol: TCP
      name: http
